### ISSUE TITLE
Chrome 404 error in the U.S. 

### ISSUE THREAD

**Issue by UncleHanzi** [Dixin/Etymology#128]
One of my friends in the U.S. is getting this 404 error when using chrome browser. I do not get the error in China. 
![0WebSite](https://user-images.githubusercontent.com/10144614/77365166-9aea8380-6d90-11ea-8245-a8b096bc3119.png)

**Comment by UncleHanzi** [comment]
She does not get the error when using Safari

**Comment by Dixin** [comment]
Repro steps?

**Comment by spectraldani** [comment]
Hi @Dixin, I think I managed to reproduce this issue.
I'm having the same problem with Chrome (ver 84.0.4147.125) but not Edge (ver 84.0.522.59).

After checking the network request from both browsers, it seems like Chrome is not sending any cookies in its request. Meanwhile, Edge is sending the GA cookies and the `Oracle` cookie. I also noted that my version of Chrome does not send the `Bronze` form data while Edge sends it correctly. I'm sure you might know what the meaning of the `Oracle` cookie and `Bronze` data is, I stopped investigating further because I'm not familiar with the system. I hope that's enough information for you to reproduce this issue :)

Feel free to ask for any other data that you might need.

**Comment by Dixin** [comment]
@spectraldani I just tried to chrome (pc and mobile) and I cannot reproduce this problem. Most of our visitors use Chrome and it works. Can you try to use a clean installation of chrome on a different machine without installing any chrome extensions, and see if it works? I am curious why the cookie is not sent.

**Comment by spectraldani** [comment]
I have just tried using a fresh installation of Chrome and still had the same problem. I investigated further with Chrome Dev Tools and I think I found the issue. [As stated here](https://web.dev/samesite-cookies-explained/#samesitenone-must-be-secure), from a certain version of Chrome on, cookies with `samesite=none` must also have the `secure` attribute.

Here's a screenshot from Devtools stating that the Set-Cookie request was blocked:
![image](https://user-images.githubusercontent.com/6686762/90264054-e9bfb500-de26-11ea-90b2-8b3666aa0520.png)

It appears that this can be fixed either by setting the `secure` attribute or by setting the cookie to `samesite=lax`. Perhaps you haven't run into this issue because of the differences in Chrome version 🤔

**Comment by Dixin** [comment]
@spectraldani Thanks for the info! What is your chrome version?

**Comment by spectraldani** [comment]
> @spectraldani Thanks for the info! What is your chrome version?

It's 84.0.4147.125

**Comment by Dixin** [comment]
@spectraldani I’ll fix this ASAP.
